
python_library(
    name='middleware',
    sources=['middleware.py'],
    dependencies=[
        # import inspect
        # import os
        # import pdb
        # import sys
        # from django.conf import settings
        # from django.core.exceptions import MiddlewareNotUsed
        # (match) from django_pdb.utils import get_ipdb, has_ipdb
        'test/path/to:target',
        # import important
    ]
)

python_library(
    name='test',
    sources=['test.py'],
    dependencies=[
        # import inspect
        # import os
        # import pdb
        # import sys
        # from django.conf import settings
        # from django.core.exceptions import MiddlewareNotUsed
        # (match) from django_pdb.utils import get_ipdb, has_ipdb
        'test/path/to:target',
    ]
)
