
python_library(
    name='test',
    sources=['test.py'],
    dependencies=[
        
    ]
)

python_library(
    name='middleware',
    sources=['middleware.py'],
    dependencies=[
        
    ]
)

python_library(
    name='test_runner',
    sources=['test_runner.py'],
    dependencies=[
        
    ]
)

