
python_library(
    name='middleware2',
    sources=['middleware2.py'],
    dependencies=[
        # (FAIL: could not find build target for import inspect)
        #import inspect
        # (FAIL: could not find build target for import os)
        #import os
        # (FAIL: could not find build target for import pdb)
        #import pdb
        # (FAIL: could not find build target for import sys)
        #import sys
        # (FAIL: could not find build target for from django.conf import settings)
        #from django.conf import settings
        # (FAIL: could not find build target for from django.core.exceptions import MiddlewareNotUsed)
        #from django.core.exceptions import MiddlewareNotUsed
        # (SUCCESS: match from target mapping) from django_pdb.utils import get_ipdb, has_ipdb
        'test/path/to:target',
    ]
)
