python_library(
    name='middleware2',
    sources=['middleware2.py'],
    dependencies=[
        # import inspect
        # import os
        # import pdb
        # import sys
        # from django.conf import settings
        # from django.core.exceptions import MiddlewareNotUsed
        # from django_pdb.utils import get_ipdb, has_ipdb
    ]
)
